# -*- coding: utf-8 -*-
"""BroadcastingMin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiDBqscGYZeAJC9E4k6ZVEd3LWUjteoG
"""

import random
import math
import matplotlib.pyplot as plt
n = [10]
missx=[] 
missy=[] 
hitx=[]
hity=[]
x2=[]
y2=[]
far=0
xL=0;
xR=100
farArrayX=[]
farArrayY=[]
hits=0
trials =10
sliceL=0
sliceR=1
temp=[]
for j in range (2):
  for i in range(trials):
      x= random.uniform(xL,xR)
      y= random.uniform(0,10)
      x2.append(x)
      y2.append(y)
  temp=x2[sliceL:sliceR]
  far=min(temp)
  xL=far
  farArrayX.append(x2[x2.index(far)])
  farArrayY.append(y2[x2.index(far)])
  xR=far+100
  sliceL=10
  sliceR=20
  print(temp)
print(farArrayY)
print(farArrayX)
#print(x2[0:9])
plt.xlabel('x - Axis.') 
plt.ylabel('y - Axis.') 
plt.scatter(x2,y2,color="green",label="Miss Points")
plt.scatter(farArrayX,farArrayY,color="red",label="head Points")
plt.legend()
plt.show()